../assets/images/
<template>
    <div id="roadmap" class="section communityfirst hmpg3 rmd20 wf-section">
        <div class="container hmpg5 rmd20 w-container">
            <div class="heading-wrapper-center inner-padding-medium">
                <div class="wrapper-black">
                    <h2 class="heading-large _20-ch"><span class="scribble"></span>Launch Roadmap</h2>
                </div>

                <p class="main-paragraph comproj mbl game">The roadmap outlines our ambition with Meta Aliens and our plans for the future.
                    The main goal is to create the first and best animated show series in the metaverse amongst other notable to be unveiled tech we are building. There are currently many new, innovative concepts we are implementing in order to provide the best experience there ever is. We believe quality comes first.</p>

                    <div class="paragraph-wrapper margin-bottom-small">

                        
                        
                        <span style="background: #1f1f1f;width: 100%; margin-bottom: 0.4em; padding: 0em 2em;">
                            
                            <h1 style="text-align: left;" class="long-x">20%</h1>

                            <span class="main-paragraph lower2 long-t" style="margin-top: 0px; color: #7a7a7a; text-align: center; display: flex; flex-wrap: wrap; justify-content: space-between; align-items: center;">
                                <p class="long-x">- The Alien Purse gets funded with 5ETH, for community needs.</p>
                                <img src="../assets/images/RM4.png" loading="lazy" width="332" alt="">
                            </span>


                        </span>

                        <span style="background: #1f1f1f;width: 100%; margin-bottom: 0.4em; padding: 0em 2em;">

                            <h1 style="text-align: right;" class="long-x">40%</h1>

                            <span class="main-paragraph lower2 long-t" style="margin-top: 0px; color: #7a7a7a; text-align: center; display: flex; flex-wrap: wrap; justify-content: space-between; align-items: center;">
                                <img src="../assets/images/RM2.png" loading="lazy" width="332" alt="">
                                <p class="long-x">- 12 aliens will be raffled to 12 active lucky holders.</p>
                            </span>

                        </span>


                        <span style="background: #1f1f1f;width: 100%; margin-bottom: 0.4em; padding: 0em 2em;">

                            <h1 style="text-align: left;" class="long-x">60%</h1>

                            <span class="main-paragraph lower2 long-t" style="margin-top: 0px; color: #7a7a7a; text-align: center; display: flex; justify-content: space-between; align-items: center;">
                                <p class="long-x">- We open our limited quantity merch store on our website which is only accessible to verified owners of Meta Aliens NFT. All profits generated by the merch store will go to (The Alien Purse) for communal use.</p>
                                <img src="../assets/images/RM3.png" loading="lazy" width="332" alt="">
                            </span>

                        </span>

                        <span style="background: #1f1f1f;width: 100%; margin-bottom: 0.4em; padding: 0em 2em;">

                            <h1 style="text-align: right;" class="long-x">80%</h1>

                            <span class="main-paragraph lower2 long-t" style="margin-top: 0px; color: #7a7a7a; text-align: center; display: flex;  justify-content: space-between; align-items: center;">
                                <img src="../assets/images/RM6.png" loading="lazy" width="332" alt="">
                                <p class="long-x">
                                    - 1x ETH weekly giveaway for 3 weeks to Meta Alien Holders.
                                            <br /><br />
                                    - Meta Alien Animated series strategy will be shared and companion features will be unveiled.
                                </p>

                            </span>

                        </span>

                        <span style="background: #1f1f1f;width: 100%; margin-bottom: 0.4em; padding: 0em 2em;">

                            <h1 style="text-align: left;" class="long-x">100%</h1>

                            <span class="main-paragraph lower2 long-t" style="margin-top: 0px; color: #7a7a7a; text-align: center; display: flex; justify-content: space-between; align-items: center;">

                                <p class="long-x">
                                    - 3 ETH of top NFTs will be raffled to lucky alien holders. <br /><br />
                                    - The first Meta Undruks companion is announced for Meta Alien holders. <br /><br />
                                    - Teaser for the (Meta Alien Wars) animated series is unveiled.
                                </p>
                                <img src="../assets/images/RM5.png" loading="lazy" width="332" alt="">
                            </span>

                        </span>

                    </div>


            </div>
        </div>
    </div>
</template>

<script>

export default {
    
    name: 'app-launch-roadmap'
}

</script>